#!/usr/bin/python
# FilenameL keyword_only

def total(initial = 5, *numbers, vegetables):
	count = initial
	for number in numbers:
		count += number
	count += vegetables
	return count

print(total(10, 1, 2, 3, vegetables = 50)
